FROM ubuntu:25.04

RUN userdel -f -r ubuntu

RUN apt-get update && apt-get install -y \
    appstream \
    bash-completion \
    build-essential \
    cmake \
    gettext \
    git \
    libadwaita-1-dev \
    libdex-dev \
    libflatpak-dev \
    libglycin-1-dev \
    libglycin-gtk4-1-dev \
    libgtk-4-dev \
    liblcms2-dev \
    libxmlb-dev \
    libyaml-dev \
    meson \
    ninja-build